# CircleCI version
version: 2

jobs:
  build:
    macos:
      xcode: "13.3.0"
    working_directory: ~/Kickstarter-Prelude
    environment:
      CIRCLE_ARTIFACTS: /tmp

    steps:
      - checkout
      - run: git submodule sync --recursive
      - run: git submodule update --init --recursive

      - run: HOMEBREW_NO_AUTO_UPDATE=1 brew install swiftlint
      - run: set -o pipefail &&
             swiftlint lint --strict --reporter json |
             tee $CIRCLE_ARTIFACTS/swiftlint-report.json
      - run: bin/test iOS 14.5
      - run: bin/test iOS 15.4
      - run: bin/test UIKit-iOS 14.5
      - run: bin/test UIKit-iOS 15.4
      - store_artifacts:
          path: /tmp/swiftlint-report.json
      - store_artifacts:
          path: /tmp/xcode_raw.log
